spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common?useSSL=false
    username: mysql
    password: "!rhcnWkwkd4"
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update